import type { Listing, Product, Store } from "./types";

export const stores: Store[] = [
  {
    id: "store-1",
    name: "GearUp UAE",
    slug: "gearup-uae",
    website: "https://gearup.example",
    sources: ["website", "instagram"],
    rating: 4.7,
    reviewCount: 842,
    warrantyMonths: 24,
    warrantyDescription: "2-year manufacturer warranty with local RMA support",
    location: "Dubai",
    logoInitials: "GU",
  },
  {
    id: "store-2",
    name: "PC Palace",
    slug: "pc-palace",
    website: "https://pcpalace.example",
    sources: ["website", "whatsapp"],
    rating: 4.5,
    reviewCount: 1203,
    warrantyMonths: 12,
    warrantyDescription: "1-year store warranty, extendable to 2 years",
    location: "Abu Dhabi",
    logoInitials: "PP",
  },
  {
    id: "store-3",
    name: "TechNest",
    slug: "technest",
    sources: ["instagram", "facebook", "whatsapp"],
    rating: 4.2,
    reviewCount: 318,
    warrantyMonths: 6,
    warrantyDescription: "6-month shop warranty on all GPUs",
    location: "Sharjah",
    logoInitials: "TN",
  },
  {
    id: "store-4",
    name: "Emirates Gaming Hub",
    slug: "emirates-gaming-hub",
    website: "https://emiratesgaming.example",
    sources: ["website", "tiktok"],
    rating: 4.9,
    reviewCount: 2104,
    warrantyMonths: 36,
    warrantyDescription: "3-year premium warranty with on-site pickup",
    location: "Dubai",
    logoInitials: "EG",
  },
  {
    id: "store-5",
    name: "Budget Builds DXB",
    slug: "budget-builds-dxb",
    sources: ["instagram", "whatsapp"],
    rating: 3.9,
    reviewCount: 156,
    warrantyMonths: 3,
    warrantyDescription: "90-day limited warranty",
    location: "Dubai",
    logoInitials: "BB",
  },
];

export const products: Product[] = [
  {
    id: "prod-1",
    name: "NVIDIA GeForce RTX 5080",
    slug: "nvidia-geforce-rtx-5080",
    brand: "NVIDIA",
    category: "Graphics Cards",
    imageEmoji: "🎮",
    specs: {
      VRAM: "16 GB GDDR7",
      "Boost Clock": "2.62 GHz",
      TDP: "320W",
      Interface: "PCIe 5.0 x16",
    },
  },
  {
    id: "prod-2",
    name: "AMD Radeon RX 9070 XT",
    slug: "amd-radeon-rx-9070-xt",
    brand: "AMD",
    category: "Graphics Cards",
    imageEmoji: "🖥️",
    specs: {
      VRAM: "16 GB GDDR6",
      "Game Clock": "2.40 GHz",
      TDP: "300W",
      Interface: "PCIe 5.0 x16",
    },
  },
  {
    id: "prod-3",
    name: "PlayStation 5 Pro",
    slug: "playstation-5-pro",
    brand: "Sony",
    category: "Consoles",
    imageEmoji: "🕹️",
    specs: {
      Storage: "2 TB SSD",
      Resolution: "Up to 8K",
      RayTracing: "Hardware accelerated",
      Region: "UAE / GCC",
    },
  },
];

export const listings: Listing[] = [
  {
    id: "list-1",
    productId: "prod-1",
    storeId: "store-1",
    price: 4299,
    currency: "AED",
    inStock: true,
    url: "https://gearup.example/rtx-5080",
    source: "website",
    warrantyMonths: 24,
    lastUpdated: "2026-06-28",
    shippingCost: 0,
    shippingDays: 1,
  },
  {
    id: "list-2",
    productId: "prod-1",
    storeId: "store-2",
    price: 4150,
    currency: "AED",
    inStock: true,
    url: "https://pcpalace.example/rtx-5080",
    source: "website",
    warrantyMonths: 12,
    lastUpdated: "2026-06-27",
    shippingCost: 25,
    shippingDays: 2,
  },
  {
    id: "list-3",
    productId: "prod-1",
    storeId: "store-3",
    price: 3999,
    currency: "AED",
    inStock: true,
    source: "instagram",
    warrantyMonths: 6,
    lastUpdated: "2026-06-29",
    shippingCost: 0,
    shippingDays: 3,
  },
  {
    id: "list-4",
    productId: "prod-1",
    storeId: "store-4",
    price: 4499,
    currency: "AED",
    inStock: true,
    url: "https://emiratesgaming.example/rtx-5080",
    source: "website",
    warrantyMonths: 36,
    lastUpdated: "2026-06-28",
    shippingCost: 0,
    shippingDays: 1,
  },
  {
    id: "list-5",
    productId: "prod-1",
    storeId: "store-5",
    price: 3899,
    currency: "AED",
    inStock: false,
    source: "whatsapp",
    warrantyMonths: 3,
    lastUpdated: "2026-06-25",
    shippingCost: 15,
    shippingDays: 4,
  },
  {
    id: "list-6",
    productId: "prod-2",
    storeId: "store-1",
    price: 3199,
    currency: "AED",
    inStock: true,
    source: "website",
    warrantyMonths: 24,
    lastUpdated: "2026-06-28",
    shippingCost: 0,
    shippingDays: 1,
  },
  {
    id: "list-7",
    productId: "prod-2",
    storeId: "store-4",
    price: 3349,
    currency: "AED",
    inStock: true,
    source: "website",
    warrantyMonths: 36,
    lastUpdated: "2026-06-27",
    shippingCost: 0,
    shippingDays: 1,
  },
  {
    id: "list-8",
    productId: "prod-3",
    storeId: "store-2",
    price: 2799,
    currency: "AED",
    inStock: true,
    source: "website",
    warrantyMonths: 12,
    lastUpdated: "2026-06-29",
    shippingCost: 0,
    shippingDays: 2,
  },
  {
    id: "list-9",
    productId: "prod-3",
    storeId: "store-4",
    price: 2699,
    currency: "AED",
    inStock: true,
    source: "website",
    warrantyMonths: 24,
    lastUpdated: "2026-06-28",
    shippingCost: 0,
    shippingDays: 1,
  },
];
